import XCTest
@testable import sweTAK

final class MQTTTests: XCTestCase {

    // MARK: - MQTT Configuration Tests

    func testMQTTConfigurationDefaults() {
        let config = MQTTConfiguration()

        XCTAssertTrue(config.host.isEmpty)
        XCTAssertEqual(config.port, 8883)
        XCTAssertTrue(config.useTLS)
        XCTAssertFalse(config.clientId.isEmpty) // UUID generated by default
    }

    func testMQTTConfigurationValidity() {
        // Empty host is invalid
        var config = MQTTConfiguration()
        XCTAssertFalse(config.isValid)

        // With host is valid
        config = MQTTConfiguration(host: "mqtt.example.com")
        XCTAssertTrue(config.isValid)

        // With TLS should use port 8883 by default
        config = MQTTConfiguration(host: "mqtt.example.com", port: 8883, useTLS: true)
        XCTAssertTrue(config.isValid)
        XCTAssertTrue(config.useTLS)
    }

    func testMQTTConfigurationCodable() throws {
        let config = MQTTConfiguration(
            host: "mqtt.example.com",
            port: 8883,
            useTLS: true,
            username: "user",
            password: "pass",
            clientId: "test-client"
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(config)

        let decoder = JSONDecoder()
        let decoded = try decoder.decode(MQTTConfiguration.self, from: data)

        XCTAssertEqual(decoded.host, config.host)
        XCTAssertEqual(decoded.port, config.port)
        XCTAssertEqual(decoded.useTLS, config.useTLS)
        XCTAssertEqual(decoded.username, config.username)
        XCTAssertEqual(decoded.password, config.password)
        XCTAssertEqual(decoded.clientId, config.clientId)
    }

    // MARK: - MQTT Topic Tests

    func testMQTTTopicConstants() {
        XCTAssertEqual(MQTTTopic.version, "v1")
        XCTAssertEqual(MQTTTopic.prefix, "swetak/v1")
        XCTAssertEqual(MQTTTopic.position, "swetak/v1/pos")
        XCTAssertEqual(MQTTTopic.pin, "swetak/v1/pin")
        XCTAssertEqual(MQTTTopic.profile, "swetak/v1/profile")
        XCTAssertEqual(MQTTTopic.chat, "swetak/v1/chat")
        XCTAssertEqual(MQTTTopic.order, "swetak/v1/order")
        XCTAssertEqual(MQTTTopic.report, "swetak/v1/report")
        XCTAssertEqual(MQTTTopic.methane, "swetak/v1/methane")
        XCTAssertEqual(MQTTTopic.medevac, "swetak/v1/medevac")
        XCTAssertEqual(MQTTTopic.linkedForm, "swetak/v1/linkedform")
    }

    func testMQTTTopicACKConstants() {
        XCTAssertEqual(MQTTTopic.orderAck, "swetak/v1/order_ack")
        XCTAssertEqual(MQTTTopic.reportAck, "swetak/v1/report_ack")
        XCTAssertEqual(MQTTTopic.methaneAck, "swetak/v1/methane_ack")
        XCTAssertEqual(MQTTTopic.medevacAck, "swetak/v1/medevac_ack")
    }

    func testMQTTTopicRequestConstants() {
        XCTAssertEqual(MQTTTopic.pinRequest, "swetak/v1/pin_req")
        XCTAssertEqual(MQTTTopic.profileRequest, "swetak/v1/profile_req")
    }

    // MARK: - Topic Routing Tests

    func testTopicForMessageType() {
        XCTAssertEqual(MQTTTopic.topic(for: .position), "swetak/v1/pos")
        XCTAssertEqual(MQTTTopic.topic(for: .pin), "swetak/v1/pin")
        XCTAssertEqual(MQTTTopic.topic(for: .pinDelete), "swetak/v1/pin")
        XCTAssertEqual(MQTTTopic.topic(for: .profile), "swetak/v1/profile")
        XCTAssertEqual(MQTTTopic.topic(for: .chat), "swetak/v1/chat")
        XCTAssertEqual(MQTTTopic.topic(for: .order), "swetak/v1/order")
        XCTAssertEqual(MQTTTopic.topic(for: .report), "swetak/v1/report")
        XCTAssertEqual(MQTTTopic.topic(for: .methane), "swetak/v1/methane")
        XCTAssertEqual(MQTTTopic.topic(for: .medevac), "swetak/v1/medevac")
        XCTAssertEqual(MQTTTopic.topic(for: .linkedForm), "swetak/v1/linkedform")
    }

    func testTopicForACKMessageTypes() {
        XCTAssertEqual(MQTTTopic.topic(for: .orderAck), "swetak/v1/order_ack")
        XCTAssertEqual(MQTTTopic.topic(for: .reportAck), "swetak/v1/report_ack")
        XCTAssertEqual(MQTTTopic.topic(for: .methaneAck), "swetak/v1/methane_ack")
        XCTAssertEqual(MQTTTopic.topic(for: .medevacAck), "swetak/v1/medevac_ack")
    }

    func testTopicForRequestTypes() {
        XCTAssertEqual(MQTTTopic.topic(for: .pinRequest), "swetak/v1/pin_req")
        XCTAssertEqual(MQTTTopic.topic(for: .hello), "swetak/v1/profile_req")
    }

    // MARK: - Network Message Tests

    func testNetworkMessageToJSON() throws {
        let message = NetworkMessage(
            type: .position,
            deviceId: "test-device-123",
            payload: [
                "callsign": "Alpha-1",
                "lat": 59.329323,
                "lon": 18.068581
            ]
        )

        let jsonData = try message.toJSONData()
        let json = try JSONSerialization.jsonObject(with: jsonData) as? [String: Any]

        XCTAssertNotNil(json)
        XCTAssertEqual(json?["type"] as? String, "pos")
        XCTAssertEqual(json?["deviceId"] as? String, "test-device-123")

        let payload = json?["payload"] as? [String: Any]
        XCTAssertEqual(payload?["callsign"] as? String, "Alpha-1")
        XCTAssertEqual(payload?["lat"] as? Double, 59.329323, accuracy: 0.0001)
    }

    func testNetworkMessageFromJSON() throws {
        let json: [String: Any] = [
            "type": "pin",
            "deviceId": "device-456",
            "timestamp": Int64(1703980800000),
            "payload": [
                "id": 12345,
                "lat": 59.0,
                "lon": 18.0,
                "title": "Test Pin"
            ]
        ]

        let data = try JSONSerialization.data(withJSONObject: json)
        let message = try NetworkMessage.fromJSONData(data)

        XCTAssertEqual(message.type, .pin)
        XCTAssertEqual(message.deviceId, "device-456")
        XCTAssertEqual(message.payload["title"] as? String, "Test Pin")
    }

    // MARK: - Message Type Tests

    func testMessageTypeRawValues() {
        // Verify raw values match Android protocol
        XCTAssertEqual(MessageType.position.rawValue, "pos")
        XCTAssertEqual(MessageType.pin.rawValue, "pin")
        XCTAssertEqual(MessageType.pinDelete.rawValue, "pin_delete")
        XCTAssertEqual(MessageType.profile.rawValue, "profile")
        XCTAssertEqual(MessageType.chat.rawValue, "chat")
        XCTAssertEqual(MessageType.order.rawValue, "order")
        XCTAssertEqual(MessageType.report.rawValue, "report")
        XCTAssertEqual(MessageType.methane.rawValue, "methane")
        XCTAssertEqual(MessageType.medevac.rawValue, "medevac")
        XCTAssertEqual(MessageType.linkedForm.rawValue, "linked_form")
    }

    func testMessageTypeACKRawValues() {
        XCTAssertEqual(MessageType.chatAck.rawValue, "chat_ack")
        XCTAssertEqual(MessageType.orderAck.rawValue, "order_ack")
        XCTAssertEqual(MessageType.reportAck.rawValue, "report_ack")
        XCTAssertEqual(MessageType.methaneAck.rawValue, "methane_ack")
        XCTAssertEqual(MessageType.medevacAck.rawValue, "medevac_ack")
    }

    // MARK: - Transport Coordinator Tests

    func testTransportCoordinatorModes() {
        let coordinator = TransportCoordinator.shared

        // Default mode should be localUDP
        XCTAssertEqual(coordinator.activeMode, .localUDP)
    }

    func testTransportModeValues() {
        XCTAssertEqual(TransportMode.localUDP.rawValue, "LOCAL_UDP")
        XCTAssertEqual(TransportMode.mqtt.rawValue, "MQTT")
    }

    // MARK: - Connection State Tests

    func testConnectionStateValues() {
        XCTAssertFalse(ConnectionState.disconnected.isConnected)
        XCTAssertFalse(ConnectionState.connecting.isConnected)
        XCTAssertTrue(ConnectionState.connected.isConnected)
        XCTAssertFalse(ConnectionState.error("test").isConnected)
    }

    // MARK: - Date Extension Tests (used by MQTT)

    func testDateCurrentMillis() {
        let before = Int64(Date().timeIntervalSince1970 * 1000)
        let currentMillis = Date.currentMillis
        let after = Int64(Date().timeIntervalSince1970 * 1000)

        XCTAssertGreaterThanOrEqual(currentMillis, before)
        XCTAssertLessThanOrEqual(currentMillis, after)
    }

    func testDateFromMillis() {
        let timestamp: Int64 = 1703980800000 // 2023-12-31 00:00:00 UTC
        let date = Date(milliseconds: timestamp)

        XCTAssertEqual(date.millisecondsSince1970, timestamp)
    }
}
