name: sweTAK iOS
options:
  bundleIdPrefix: com.Nerio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  CocoaMQTT:
    url: https://github.com/emqx/CocoaMQTT.git
    from: "2.1.6"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "sweTAK needs your location to display your position on the tactical map"
    INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "sweTAK needs your location to track your position and record breadcrumb trails"
    INFOPLIST_KEY_NSCameraUsageDescription: "sweTAK needs camera access to capture photos for photo pins"

targets:
  sweTAK iOS:
    type: application
    platform: iOS
    sources:
      - path: "sweTAK iOS"
        excludes:
          - "**/.DS_Store"
    info:
      path: "sweTAK iOS/Info.plist"
      properties:
        CFBundleDisplayName: sweTAK
        UILaunchScreen: {}
        UIBackgroundModes:
          - location
        NSLocationWhenInUseUsageDescription: "sweTAK needs your location to display your position on the tactical map"
        NSLocationAlwaysAndWhenInUseUsageDescription: "sweTAK needs your location to track your position and record breadcrumb trails"
        NSCameraUsageDescription: "sweTAK needs camera access to capture photos for photo pins"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.Nerio.sweTAK
        PRODUCT_NAME: sweTAK
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: CocoaMQTT

  sweTAK iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: "sweTAK iOSTests"
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.Nerio.sweTAK.tests
    dependencies:
      - target: sweTAK iOS

  sweTAK iOSUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: "sweTAK iOSUITests"
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.Nerio.sweTAK.uitests
    dependencies:
      - target: sweTAK iOS

schemes:
  sweTAK iOS:
    build:
      targets:
        sweTAK iOS: all
        sweTAK iOSTests: [test]
        sweTAK iOSUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - sweTAK iOSTests
        - sweTAK iOSUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
